nodeLinker: node-modules

npmScopes:
  pulselabs-ai:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com/"
    npmAuthToken: "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"

yarnPath: .yarn/releases/yarn-4.7.0.cjs
